spring: 
  profiles:
    active: dev
  application:
    name: provider-user
  jackson:
    default-property-inclusion: non-null

management:
  security:
    enabled: false

logging:
  config: classpath:logback-boot.xml
  path: /project/logs/microservice-springcloud/provider-user

info: 
  app.name: microservice-springcloud
  company.name: https://spring.io/projects/spring-cloud
    
---
spring:
  profiles: dev
 
server:
  port: 8002
  tomcat:
    uri-encoding: UTF-8
      
eureka:
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/
  instance: 
    instance-id: provider-user-01
    prefer-ip-address: true
    metadata-map:
      group: springcloud-group
      version: ${server.port}
        
---
spring:
  profiles: test
server:
  port: 8002
  tomcat:
      uri-encoding: UTF-8
    
eureka:
  client: 
    service-url: 
      defaultZone: http://eureka-01:7001/eureka/,http://eureka-02:7001/eureka/
  instance:
    instance-id: ${instanceId}
    prefer-ip-address: true
    metadata-map:
      group: springcloud-group
      version: ${server.port}